### ISSUE TITLE
Cats menu empty

### ISSUE THREAD

**Issue by fmfernandes** [scripting/a8c-FeedLand-Support#27]
When logged out and viewing the [index page](https://a8c.feedland.org/), the Cats menu is empty. Would be better if we hide it. What do you think @scripting?

<img width="3792" alt="Screenshot on 2023-10-20 at 12:41:59" src="https://github.com/scripting/a8c-FeedLand-Support/assets/24195829/4c5cf002-326a-4b28-a4e0-9656e27884fc">

**Comment by scripting** [comment]
Fixed.
