### ISSUE TITLE
Setting up a GitHub Project board

### ISSUE THREAD

**Issue by cagrimmett** [scripting/a8c-FeedLand-Support#37]
Hi @scripting!

Here are the steps to set up a project board so I can populate it:

1. Go to https://github.com/scripting?tab=projects
2. Click the green "New project" button
3. It prompts you to select a template. The default Table is fine, so just click Create.
4. You should see the main project screen. In the upper right, click the horizontal three dots button and Settings. It should take you to the project settings page.
5. In the left side of the settings page, click Manage Access. 
6. In the Invite Collaborators section, invite `cagrimmett` with the role Admin and click Invite (This only lets me admin the project board, not your account or repositories.)
7. I'll take care of the rest.

Thank you!

**Comment by scripting** [comment]
@cagrimmett -- thanks for your patience on this. i've done as you requested. ;-)
