### ISSUE TITLE
Bug: View As links are returning undefined

### ISSUE THREAD

**Issue by cagrimmett** [scripting/a8c-FeedLand-Support#72]
Seeing this on both feedland.org and feedland.com. Must have been an unintended consequence of a recent change, because this was working as of Friday I think.

Steps to reproduce:
1. Go to Menu > My feed list...
2. Click on a feed to go to the Feed info page. For example, https://feedland.com/?feedurl=https%3A%2F%2Fcagrimmett.com%2Ffeed%2F
3. Under the View as: section, click on either river or mailbox. 
4. You'll get redirected to `https://feedland.com/?river=undefined`

These errors show in the console:
<img width="1135" alt="image" src="https://github.com/scripting/a8c-FeedLand-Support/assets/8738771/d8cbd479-e078-42a4-8267-d93e684044c5">

**Comment by scripting** [comment]
Thanks for the report. Fixed.
