### ISSUE TITLE
Feed name in user info page

### ISSUE THREAD

**Issue by fmfernandes** [scripting/a8c-FeedLand-Support#80]
Some users have a blank feed name and some have an `undefined` as their feed name.

I was able to reproduce the blank feed name by going to my settings screen and changing my feed title to an empty string and clicking on save. This is my [user page](https://feedland.com/?userinfo=fernando#).

I believe the feed title there should have be the feed title otherwise a default `feed` text if title is empty.

`undefined` seems to be the initial state when a user signs up. If the user signs up and check the settings screen, the undefined will be replaced with a blank name.

**Comment by scripting** [comment]
The default values for the feed title and description are in appPrefs.myFeedTitle and appPrefs.myFeedDescription.

```
myFeedTitle: "My Feed",
myFeedDescription: "The feed for my FeedLand notes.",

```
I'm pretty confident that code works, it's been that that way for many years, without error.

It's more likely there was some problem at some point with static storage. 

Do you know how long ago the accounts for these users were created?

**Comment by scripting** [comment]
You can find the declaration for appPrefs at the top of http://scripting.com/code/feedland/home/code.js.

**Comment by scripting** [comment]
Interesting. It's happening this way on feedland.org too. Hmm.

**Comment by scripting** [comment]
@fmfernandes -- what about other settings, are any of them undefined too? mostly they come from the same places.

**Comment by scripting** [comment]
@fmfernandes -- you win 10 points, it's a legit bug, in feedlandHome, which is now fixed. 

Do a hard reload of, and try it again with a new account. 

Thank you.
